// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHt_fz3bALSICHrRsALnU9HNLy05XZ3eE',
    appId: '1:1030646285472:web:1ce9c55c587c11c028f5c5',
    messagingSenderId: '1030646285472',
    projectId: 'chatapp-be890',
    authDomain: 'chatapp-be890.firebaseapp.com',
    storageBucket: 'chatapp-be890.firebasestorage.app',
    measurementId: 'G-0076ZZQF58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKArBuESC9LC5of0eDcUlGvdMNe7Xvnbc',
    appId: '1:1030646285472:android:8379356e1196584f28f5c5',
    messagingSenderId: '1030646285472',
    projectId: 'chatapp-be890',
    storageBucket: 'chatapp-be890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM77M440KXq7UV71-Djx22Q_AgAFHzrQw',
    appId: '1:1030646285472:ios:0499c1d33051173328f5c5',
    messagingSenderId: '1030646285472',
    projectId: 'chatapp-be890',
    storageBucket: 'chatapp-be890.firebasestorage.app',
    iosClientId: '1030646285472-mns1atq2picomq72a43ljcqbp0hri1gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM77M440KXq7UV71-Djx22Q_AgAFHzrQw',
    appId: '1:1030646285472:ios:0499c1d33051173328f5c5',
    messagingSenderId: '1030646285472',
    projectId: 'chatapp-be890',
    storageBucket: 'chatapp-be890.firebasestorage.app',
    iosClientId: '1030646285472-mns1atq2picomq72a43ljcqbp0hri1gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHt_fz3bALSICHrRsALnU9HNLy05XZ3eE',
    appId: '1:1030646285472:web:7e18de49d46a7daf28f5c5',
    messagingSenderId: '1030646285472',
    projectId: 'chatapp-be890',
    authDomain: 'chatapp-be890.firebaseapp.com',
    storageBucket: 'chatapp-be890.firebasestorage.app',
    measurementId: 'G-K3S7RD8D3M',
  );
}
